### ISSUE TITLE
Publish compilable at Arch User Repository

### ISSUE THREAD

**Issue by ghost** [ros-perception/laser_assembler#18]
So i am very new to ROS and i ran into some hustle installing it on Arch.

Because the current commit https://github.com/ros-perception/laser_assembler/pull/16 which is needed to build with boost 1.68 is not in the AUR.
First of all I found that very outdated wiki page about boost which is plain wrong and misleading:
[http://wiki.ros.org/boost](http://wiki.ros.org/boost)
Then, after realising it has no use and wouldn't work anyway to build boost 1.35 on my own,
I realized that I may [patch ](https://wiki.archlinux.org/index.php/Patching_packages) the AUR-Package of [ros-melodic-laser-assembler](https://aur.archlinux.org/packages/ros-melodic-laser-assembler/) and it did work quite well.
In the end I came here to brag and then i even saw that you already fixed that issue month ago but did not publish it with AUR.
Please, for the sanity of every newbie, do that. It helps a lot and the build process takes long enough without weird debugging.

**Comment by jonbinney** [comment]
Hmmm - I've no idea what the Arch User Repository is. Presumably that is something that gets filled in by the release process?

**Comment by ghost** [comment]
Thanks for the quick reply.

["The Arch User Repository (AUR) is a community-driven repository for Arch users."](https://wiki.archlinux.org/index.php/Arch_User_Repository)
I know, this is a very specific problem, but ROS devs seem to relate to it, by publishing there.
Also I am quite certain that the updates happen after the release, but not coupled, because the release dates in git and AUR differ in weeks.

But in my opinion bugs that break compilation should be pushed right away or at least should be mentioned in the [ros wiki](http://wiki.ros.org/melodic/Installation/ArchLinux).
Maybe you can point me to the right repo to provide a PR to the ROS wiki?

**Comment by jonbinney** [comment]
@SemjonKerner I'm still not sure how the code is getting from this repo to AUR, so not sure how to fix this.

**Comment by CBJamo** [comment]
The AUR doesn't store releases, just instructions to build a package in the form of a [pkgbuild](https://wiki.archlinux.org/index.php/PKGBUILD) and patches. When a user does an install from the AUR, they grab the pkgbuild and run makepkg against it. makepkg downloads the needed source and does a local build, then tars up a final package to be installed.

All that needs to be done on your end to fix this for arch users is to push a current release. Will #16 cause issues with users of older versions of boost?

**Comment by ghost** [comment]
> Will #16 cause issues with users of older versions of boost?

As [mentioned in the issue](https://github.com/ros/actionlib/pull/105#issuecomment-384836716) that was resolved by #16 there was already a typecast necessary, but with boost 1.67 it became mandatory to pass an int64. So this fix could have been made, but was not urgent in earlier versions. So no, there should be no problems with older boost versions, at least up to 1.54.

**Comment by CBJamo** [comment]
Excelent, @jonbinney should be good to make a release. The oldest relevant Ubuntu release (Trusty), has boost 1.54.

**Comment by jonbinney** [comment]
@CBJamo @SemjonKerner thanks for investigating this. I'll make a release soon to fix the issue.

**Comment by ghost** [comment]
Great, thank you!
There is one point left: The wiki should be changed. I guess it makes sense to delete the [http://wiki.ros.org/boost](boost) page completely, in case ROS keeps using the latest version. Also it could also be a good idea to mention that fixes might be available on github, in the [Installation Instructions](http://wiki.ros.org/melodic/Installation). If the wiki wasn't misleading I probably had looked into github way earlier.

**Comment by jonbinney** [comment]
Oh wow that boost wiki page is waaaay out of date. At the bottom it says last modified "2010-03-04". I went ahead and deleted it.

I haven't done the release of this package yet - might not get to that until monday.

**Comment by jonbinney** [comment]
I justreleased version 1.7.6 into melodic: https://github.com/ros/rosdistro/pull/19506

**Comment by CBJamo** [comment]
You can close this issue, everything that needs to be done on your end is good to go. Thanks for the quick turnaround.
