### ISSUE TITLE
Create ros2-crystal branch

### ISSUE THREAD

**Issue by vandanamandlik** [ros-perception/laser_assembler#22]
I am porting laser_assembler package for crystal. Request you to create new branch for it so that I can raise a Pull request.

**Comment by jonbinney** [comment]
How different is the code for crystal compared to the bouncy code in https://github.com/ros-perception/laser_assembler/pull/21 ?

**Comment by vandanamandlik** [comment]
I have done following two changes for crystal

1. Replaced manual conversion of nanoseconds to seconds with function seconds() in message_filter.hpp
   - rclcpp::Time class of Bouncy was not having seconds() function but now its available in crystal so used it here.
   
    - https://github.com/vandanamandlik/laser_assembler/commit/5dbb9846b4c39a3087cde5c197d55ddcd62cd1d8
   
2. Removed manually clone and build steps of message_filters and launch package from readme because now it available in crystal, Changed raw pointer to shared_pointer.

    - https://github.com/vandanamandlik/laser_assembler/commit/4995443c6c76e3768d0f7ca2902078ab38216dcf
    - message filter package was not there in bouncy, So in order to build laser assembler
      I was cloning and buiding it from intel message filter repository.
      Now its available in crystal release so that step is skipped in crystal.

    - launch package was not fully ported in bouncy so there I was using master branch of launch packge repository. But now its available in crystal so this step is also skipped in crystal.

    - Changed raw pointer to shared pointer in base_assembler.hpp
        subscribe method of intel's message_filters package was accepting raw node pointer only,
        virtual void subscribe(rclcpp::Node * node, const std::string& topic, const rmw_qos_profile_t qos = rmw_qos_profile_default) = 0;
        In crystal subscribe() method can accept shared_pointer so changed raw pointer to shared_pointer in crystal.

**Comment by jonbinney** [comment]
@vandanamandlik thanks for the explanation. I've created the new branch here: https://github.com/ros-perception/laser_assembler/tree/ros2-crystal

**Comment by vandanamandlik** [comment]
Thanks for creating branch
