### ISSUE TITLE
Release laser_assembler to Noetic?

### ISSUE THREAD

**Issue by ahcorde** [ros-perception/laser_assembler#29]
Would you mind releasing laser_filters to ROS Noetic? It looks like all of its dependencies have been released, and recursively 3 repos need it.

I'm not sure how much work it will need. At a minimum it needs #28.

**Comment by jonbinney** [comment]
Created a noetic-devel branch. Will release once https://github.com/ros-perception/laser_assembler/pull/28 has been retargeted and merged.

**Comment by jonbinney** [comment]
Now I just need to setup a docker container with 20.04 to make sure everything builds. Will try to do that and release tomorrow.

**Comment by jonbinney** [comment]
Screw it, i went ahead and did the release. Hopefully everything builds... https://github.com/ros/rosdistro/pull/24419

**Comment by sloretz** [comment]
Thank you! [It looks happy](http://build.ros.org/job/Nbin_uF64__laser_assembler__ubuntu_focal_amd64__binary/).
