### ISSUE TITLE
update the matainer's email address

### ISSUE THREAD

**Issue by vrabaud** [ros-perception/laser_assembler#5]
Plus, it was wrong in the first place :)

**Comment by vrabaud** [comment]
@dgossow  , you're a maintainer on that package but I am not sure you are watching it. You have a few very easy bugs.

**Comment by dgossow** [comment]
dgossoe? That must be someone else.

No, seriously, I think this should read "find new maintainer". Maybe @vpradeep07 wants to take it back?

**Comment by vpradeep07** [comment]
It probably makes the most sense for a consumer of this code to actually be the maintainer.  If we can't find anyone using this code, then it doesn't feel so bad to let it die.

**Comment by jonbinney** [comment]
I'm maintaining for now - maintainer email has been updated.
